// Mocks generated by Mockito 5.4.6 from annotations
// in pet_app/test/features/home/data/repo_impl/breeds_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pet_app/core/network/network_info.dart' as _i2;
import 'package:pet_app/features/home/data/data_source/breeds_locale_data_source.dart'
    as _i6;
import 'package:pet_app/features/home/data/data_source/breeds_remote_data_source.dart'
    as _i4;
import 'package:pet_app/features/home/data/models/breeds_model.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i2.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}

/// A class which mocks [BreedsRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBreedsRemoteDataSource extends _i1.Mock
    implements _i4.BreedsRemoteDataSource {
  MockBreedsRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i5.BreedModel>> getBreeds({
    required int? page,
    required int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getBreeds, [], {#page: page, #limit: limit}),
            returnValue: _i3.Future<List<_i5.BreedModel>>.value(
              <_i5.BreedModel>[],
            ),
          )
          as _i3.Future<List<_i5.BreedModel>>);
}

/// A class which mocks [BreedsLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBreedsLocalDataSource extends _i1.Mock
    implements _i6.BreedsLocalDataSource {
  MockBreedsLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> cacheBreeds(List<_i5.BreedModel>? breeds) =>
      (super.noSuchMethod(
            Invocation.method(#cacheBreeds, [breeds]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.BreedModel>> getCachedBreeds() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedBreeds, []),
            returnValue: _i3.Future<List<_i5.BreedModel>>.value(
              <_i5.BreedModel>[],
            ),
          )
          as _i3.Future<List<_i5.BreedModel>>);

  @override
  _i3.Future<void> clearCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
